### ISSUE TITLE
can you help me to solve the problem about "MessageBodyWriter not found "

### ISSUE THREAD

**Issue by leenova** [AlanHohn/jaxrs#1]
This is error message
org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor aroundWriteTo
严重: MessageBodyWriter not found for media type={text/html, q=1000}, type=class org.anvard.jaxrs.api.Calculation, genericType=class org.anvard.jaxrs.api.Calculation.

**Comment by AlanHohn** [comment]
I don't have a lot of detail as to how you're using the code to get this error, so this will be a little bit of a guess. Most likely, you're trying to visit a REST URL endpoint directly in the browser.

The issue that you're facing is that Jersey does not know how to turn a "Calculation" object into HTML. To get HTML as the response there would have to be a class that implements MessageBodyWriter<Calculation> and is annotated with @Produces("text/html").

But that wouldn't really suit the purpose of this example; the idea is to have a REST endpoint that could be called from code (client software, or JavaScript in the browser) that would produce JSON or XML. Then the code would parse the JSON or XML and use it to update a display (thick client or web application in a browser).

You can see an example of this in src/main/webapp; the HTML and JavaScript are served by the application as static files, and the JavaScript then uses jQuery to invoke the REST endpoint, retrieve JSON, parse it, and update the page.

If you want to hit the REST endpoint directly from a browser, you'll need a way to include the right "Accept" HTTP header in your request. The best way to do this is with a REST client plugin for your browser.
