### ISSUE TITLE
MessageBodyWriter not found

### ISSUE THREAD

**Issue by jcaristi** [AlanHohn/jaxrs#2]
After building the application with "mvn install", I executed "mvn jetty:run".  I then navigated to http://localhost:8680/ where I got a web page that shows this path "/rest/calculator/calc/add/2/2".  I tried to hit this URL: "http://localhost:8680/rest/calculator/calc/add/2/2" and I got the following error:

 Oct 26, 2018 11:38:54 AM org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor aroundWriteTo
SEVERE: MessageBodyWriter not found for media type={text/html, q=1000}, type=class org.anvard.jaxrs.api.Calculation, genericType=class org.anvard.jaxrs.api.Calculation.

**Comment by AlanHohn** [comment]
Jersey is using the "Accept" header of the HTTP request to determine what format you want for the output. When you hit the link in your browser, the server thinks you want HTML but doesn't have a way to make HTML from the output of that method. 

To hit the endpoint and get a response, try using a REST client like httpie, or try it from Curl while manually providing an Accept header of "application/json".
